/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  border: {
    none: {
      key: "{border.none}",
      value: 0,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 0,
        key: "{border.none}",
      },
      name: "BorderNone",
      attributes: {
        category: "border",
        type: "none",
      },
      path: ["border", "none"],
    },
    sm: {
      key: "{border.sm}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.sm}",
      },
      name: "BorderSm",
      attributes: {
        category: "border",
        type: "sm",
      },
      path: ["border", "sm"],
    },
    md: {
      key: "{border.md}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.md}",
      },
      name: "BorderMd",
      attributes: {
        category: "border",
        type: "md",
      },
      path: ["border", "md"],
    },
    lg: {
      key: "{border.lg}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.lg}",
      },
      name: "BorderLg",
      attributes: {
        category: "border",
        type: "lg",
      },
      path: ["border", "lg"],
    },
    full: {
      key: "{border.full}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.full}",
      },
      name: "BorderFull",
      attributes: {
        category: "border",
        type: "full",
      },
      path: ["border", "full"],
    },
    thin: {
      key: "{border.thin}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.thin}",
      },
      name: "BorderThin",
      attributes: {
        category: "border",
        type: "thin",
      },
      path: ["border", "thin"],
    },
    medium: {
      key: "{border.medium}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.medium}",
      },
      name: "BorderMedium",
      attributes: {
        category: "border",
        type: "medium",
      },
      path: ["border", "medium"],
    },
    thick: {
      key: "{border.thick}",
      value: 4,
      filePath: "tokens/border.json",
      isSource: true,
      original: {
        value: 4,
        key: "{border.thick}",
      },
      name: "BorderThick",
      attributes: {
        category: "border",
        type: "thick",
      },
      path: ["border", "thick"],
    },
  },
  color: {
    base: {
      white: {
        key: "{color.base.white}",
        value: "#ffffff",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#ffffff",
          key: "{color.base.white}",
        },
        name: "ColorBaseWhite",
        attributes: {
          category: "color",
          type: "base",
          item: "white",
        },
        path: ["color", "base", "white"],
      },
      black: {
        key: "{color.base.black}",
        value: "#000000",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#000000",
          key: "{color.base.black}",
        },
        name: "ColorBaseBlack",
        attributes: {
          category: "color",
          type: "base",
          item: "black",
        },
        path: ["color", "base", "black"],
      },
      gray: {
        100: {
          key: "{color.base.gray.100}",
          value: "#f7fafc",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#f7fafc",
            key: "{color.base.gray.100}",
          },
          name: "ColorBaseGray100",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "100",
          },
          path: ["color", "base", "gray", "100"],
        },
        200: {
          key: "{color.base.gray.200}",
          value: "#edf2f7",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#edf2f7",
            key: "{color.base.gray.200}",
          },
          name: "ColorBaseGray200",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "200",
          },
          path: ["color", "base", "gray", "200"],
        },
        300: {
          key: "{color.base.gray.300}",
          value: "#e2e8f0",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#e2e8f0",
            key: "{color.base.gray.300}",
          },
          name: "ColorBaseGray300",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "300",
          },
          path: ["color", "base", "gray", "300"],
        },
        400: {
          key: "{color.base.gray.400}",
          value: "#cbd5e0",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#cbd5e0",
            key: "{color.base.gray.400}",
          },
          name: "ColorBaseGray400",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "400",
          },
          path: ["color", "base", "gray", "400"],
        },
        500: {
          key: "{color.base.gray.500}",
          value: "#a0aec0",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#a0aec0",
            key: "{color.base.gray.500}",
          },
          name: "ColorBaseGray500",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "500",
          },
          path: ["color", "base", "gray", "500"],
        },
        600: {
          key: "{color.base.gray.600}",
          value: "#718096",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#718096",
            key: "{color.base.gray.600}",
          },
          name: "ColorBaseGray600",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "600",
          },
          path: ["color", "base", "gray", "600"],
        },
        700: {
          key: "{color.base.gray.700}",
          value: "#4a5568",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#4a5568",
            key: "{color.base.gray.700}",
          },
          name: "ColorBaseGray700",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "700",
          },
          path: ["color", "base", "gray", "700"],
        },
        800: {
          key: "{color.base.gray.800}",
          value: "#2d3748",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#2d3748",
            key: "{color.base.gray.800}",
          },
          name: "ColorBaseGray800",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "800",
          },
          path: ["color", "base", "gray", "800"],
        },
        900: {
          key: "{color.base.gray.900}",
          value: "#1a202c",
          filePath: "tokens/color.json",
          isSource: true,
          original: {
            value: "#1a202c",
            key: "{color.base.gray.900}",
          },
          name: "ColorBaseGray900",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "900",
          },
          path: ["color", "base", "gray", "900"],
        },
      },
    },
    brand: {
      primary: {
        key: "{color.brand.primary}",
        value: "#3b82f6",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#3b82f6",
          key: "{color.brand.primary}",
        },
        name: "ColorBrandPrimary",
        attributes: {
          category: "color",
          type: "brand",
          item: "primary",
        },
        path: ["color", "brand", "primary"],
      },
      secondary: {
        key: "{color.brand.secondary}",
        value: "#8b5cf6",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#8b5cf6",
          key: "{color.brand.secondary}",
        },
        name: "ColorBrandSecondary",
        attributes: {
          category: "color",
          type: "brand",
          item: "secondary",
        },
        path: ["color", "brand", "secondary"],
      },
      accent: {
        key: "{color.brand.accent}",
        value: "#ec4899",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#ec4899",
          key: "{color.brand.accent}",
        },
        name: "ColorBrandAccent",
        attributes: {
          category: "color",
          type: "brand",
          item: "accent",
        },
        path: ["color", "brand", "accent"],
      },
    },
    semantic: {
      success: {
        key: "{color.semantic.success}",
        value: "#10b981",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#10b981",
          key: "{color.semantic.success}",
        },
        name: "ColorSemanticSuccess",
        attributes: {
          category: "color",
          type: "semantic",
          item: "success",
        },
        path: ["color", "semantic", "success"],
      },
      warning: {
        key: "{color.semantic.warning}",
        value: "#f59e0b",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#f59e0b",
          key: "{color.semantic.warning}",
        },
        name: "ColorSemanticWarning",
        attributes: {
          category: "color",
          type: "semantic",
          item: "warning",
        },
        path: ["color", "semantic", "warning"],
      },
      error: {
        key: "{color.semantic.error}",
        value: "#ef4444",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#ef4444",
          key: "{color.semantic.error}",
        },
        name: "ColorSemanticError",
        attributes: {
          category: "color",
          type: "semantic",
          item: "error",
        },
        path: ["color", "semantic", "error"],
      },
      info: {
        key: "{color.semantic.info}",
        value: "#3b82f6",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "#3b82f6",
          key: "{color.semantic.info}",
        },
        name: "ColorSemanticInfo",
        attributes: {
          category: "color",
          type: "semantic",
          item: "info",
        },
        path: ["color", "semantic", "info"],
      },
    },
    text: {
      primary: {
        key: "{color.text.primary}",
        value: "#1a202c",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "{color.base.gray.900}",
          key: "{color.text.primary}",
        },
        name: "ColorTextPrimary",
        attributes: {
          category: "color",
          type: "text",
          item: "primary",
        },
        path: ["color", "text", "primary"],
      },
      secondary: {
        key: "{color.text.secondary}",
        value: "#718096",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "{color.base.gray.600}",
          key: "{color.text.secondary}",
        },
        name: "ColorTextSecondary",
        attributes: {
          category: "color",
          type: "text",
          item: "secondary",
        },
        path: ["color", "text", "secondary"],
      },
      disabled: {
        key: "{color.text.disabled}",
        value: "#cbd5e0",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "{color.base.gray.400}",
          key: "{color.text.disabled}",
        },
        name: "ColorTextDisabled",
        attributes: {
          category: "color",
          type: "text",
          item: "disabled",
        },
        path: ["color", "text", "disabled"],
      },
    },
    background: {
      primary: {
        key: "{color.background.primary}",
        value: "#ffffff",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "{color.base.white}",
          key: "{color.background.primary}",
        },
        name: "ColorBackgroundPrimary",
        attributes: {
          category: "color",
          type: "background",
          item: "primary",
        },
        path: ["color", "background", "primary"],
      },
      secondary: {
        key: "{color.background.secondary}",
        value: "#f7fafc",
        filePath: "tokens/color.json",
        isSource: true,
        original: {
          value: "{color.base.gray.100}",
          key: "{color.background.secondary}",
        },
        name: "ColorBackgroundSecondary",
        attributes: {
          category: "color",
          type: "background",
          item: "secondary",
        },
        path: ["color", "background", "secondary"],
      },
    },
  },
  font: {
    family: {
      heading: {
        key: "{font.family.heading}",
        value: "'Poppins', sans-serif",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "'Poppins', sans-serif",
          key: "{font.family.heading}",
        },
        name: "FontFamilyHeading",
        attributes: {
          category: "font",
          type: "family",
          item: "heading",
        },
        path: ["font", "family", "heading"],
      },
    },
    size: {
      xs: {
        key: "{font.size.xs}",
        value: "12px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "12px",
          key: "{font.size.xs}",
        },
        name: "FontSizeXs",
        attributes: {
          category: "font",
          type: "size",
          item: "xs",
        },
        path: ["font", "size", "xs"],
      },
      sm: {
        key: "{font.size.sm}",
        value: "14px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "14px",
          key: "{font.size.sm}",
        },
        name: "FontSizeSm",
        attributes: {
          category: "font",
          type: "size",
          item: "sm",
        },
        path: ["font", "size", "sm"],
      },
      base: {
        key: "{font.size.base}",
        value: "16px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "16px",
          key: "{font.size.base}",
        },
        name: "FontSizeBase",
        attributes: {
          category: "font",
          type: "size",
          item: "base",
        },
        path: ["font", "size", "base"],
      },
      lg: {
        key: "{font.size.lg}",
        value: "18px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "18px",
          key: "{font.size.lg}",
        },
        name: "FontSizeLg",
        attributes: {
          category: "font",
          type: "size",
          item: "lg",
        },
        path: ["font", "size", "lg"],
      },
      xl: {
        key: "{font.size.xl}",
        value: "20px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "20px",
          key: "{font.size.xl}",
        },
        name: "FontSizeXl",
        attributes: {
          category: "font",
          type: "size",
          item: "xl",
        },
        path: ["font", "size", "xl"],
      },
      "2xl": {
        key: "{font.size.2xl}",
        value: "24px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "24px",
          key: "{font.size.2xl}",
        },
        name: "FontSize2xl",
        attributes: {
          category: "font",
          type: "size",
          item: "2xl",
        },
        path: ["font", "size", "2xl"],
      },
      "3xl": {
        key: "{font.size.3xl}",
        value: "30px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "30px",
          key: "{font.size.3xl}",
        },
        name: "FontSize3xl",
        attributes: {
          category: "font",
          type: "size",
          item: "3xl",
        },
        path: ["font", "size", "3xl"],
      },
      "4xl": {
        key: "{font.size.4xl}",
        value: "36px",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "36px",
          key: "{font.size.4xl}",
        },
        name: "FontSize4xl",
        attributes: {
          category: "font",
          type: "size",
          item: "4xl",
        },
        path: ["font", "size", "4xl"],
      },
    },
    weight: {
      light: {
        key: "{font.weight.light}",
        value: "300",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "300",
          key: "{font.weight.light}",
        },
        name: "FontWeightLight",
        attributes: {
          category: "font",
          type: "weight",
          item: "light",
        },
        path: ["font", "weight", "light"],
      },
      normal: {
        key: "{font.weight.normal}",
        value: "400",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "400",
          key: "{font.weight.normal}",
        },
        name: "FontWeightNormal",
        attributes: {
          category: "font",
          type: "weight",
          item: "normal",
        },
        path: ["font", "weight", "normal"],
      },
      medium: {
        key: "{font.weight.medium}",
        value: "500",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "500",
          key: "{font.weight.medium}",
        },
        name: "FontWeightMedium",
        attributes: {
          category: "font",
          type: "weight",
          item: "medium",
        },
        path: ["font", "weight", "medium"],
      },
      semibold: {
        key: "{font.weight.semibold}",
        value: "600",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "600",
          key: "{font.weight.semibold}",
        },
        name: "FontWeightSemibold",
        attributes: {
          category: "font",
          type: "weight",
          item: "semibold",
        },
        path: ["font", "weight", "semibold"],
      },
      bold: {
        key: "{font.weight.bold}",
        value: "700",
        filePath: "tokens/font.json",
        isSource: true,
        original: {
          value: "700",
          key: "{font.weight.bold}",
        },
        name: "FontWeightBold",
        attributes: {
          category: "font",
          type: "weight",
          item: "bold",
        },
        path: ["font", "weight", "bold"],
      },
    },
  },
  padding: {
    sm: {
      key: "{padding.sm}",
      type: "spacing",
      value: "8px",
      description: "",
      filePath: "tokens/padding.json",
      isSource: true,
      original: {
        type: "spacing",
        value: "{spacing.sm}",
        description: "",
        key: "{padding.sm}",
      },
      name: "PaddingSm",
      attributes: {
        category: "padding",
        type: "sm",
      },
      path: ["padding", "sm"],
    },
    xs: {
      key: "{padding.xs}",
      type: "spacing",
      value: "4px",
      description: "",
      filePath: "tokens/padding.json",
      isSource: true,
      original: {
        type: "spacing",
        value: "{spacing.xs}",
        description: "",
        key: "{padding.xs}",
      },
      name: "PaddingXs",
      attributes: {
        category: "padding",
        type: "xs",
      },
      path: ["padding", "xs"],
    },
  },
  spacing: {
    xs: {
      key: "{spacing.xs}",
      value: "4px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "4px",
        key: "{spacing.xs}",
      },
      name: "SpacingXs",
      attributes: {
        category: "spacing",
        type: "xs",
      },
      path: ["spacing", "xs"],
    },
    sm: {
      key: "{spacing.sm}",
      value: "8px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "8px",
        key: "{spacing.sm}",
      },
      name: "SpacingSm",
      attributes: {
        category: "spacing",
        type: "sm",
      },
      path: ["spacing", "sm"],
    },
    md: {
      key: "{spacing.md}",
      value: "16px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "16px",
        key: "{spacing.md}",
      },
      name: "SpacingMd",
      attributes: {
        category: "spacing",
        type: "md",
      },
      path: ["spacing", "md"],
    },
    lg: {
      key: "{spacing.lg}",
      value: "24px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "24px",
        key: "{spacing.lg}",
      },
      name: "SpacingLg",
      attributes: {
        category: "spacing",
        type: "lg",
      },
      path: ["spacing", "lg"],
    },
    xl: {
      key: "{spacing.xl}",
      value: "32px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "32px",
        key: "{spacing.xl}",
      },
      name: "SpacingXl",
      attributes: {
        category: "spacing",
        type: "xl",
      },
      path: ["spacing", "xl"],
    },
    xxl: {
      key: "{spacing.xxl}",
      value: "48px",
      filePath: "tokens/spacing.json",
      isSource: true,
      original: {
        value: "48px",
        key: "{spacing.xxl}",
      },
      name: "SpacingXxl",
      attributes: {
        category: "spacing",
        type: "xxl",
      },
      path: ["spacing", "xxl"],
    },
  },
};
